version: '3.3'

services:
  api:
    build:
      context: .
      dockerfile: src/Dockerfile
    restart: on-failure
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: horoscope_adviser
      POSTGRES_PASSWORD: horoscope_adviser
      POSTGRES_DB: horoscope_adviser
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  db:
    image: postgres:15.2
    restart: on-failure
    environment:
      POSTGRES_USER: horoscope_adviser
      POSTGRES_PASSWORD: horoscope_adviser
      POSTGRES_DB: horoscope_adviser
      POSTGRES_PORT: 5432
