"""Added unique constraint to subscription

Revision ID: ea1c47c71da1
Revises: c034da489b9a
Create Date: 2023-09-30 09:46:23.379289

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "ea1c47c71da1"
down_revision = "c034da489b9a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("subscriptions_user_id_key", "subscriptions", type_="unique")
    op.create_unique_constraint(op.f("subscriptions_user_id_key"), "subscriptions", ["user_id"])
    op.create_unique_constraint(op.f("users_telegram_user_id_key"), "users", ["telegram_user_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("users_telegram_user_id_key"), "users", type_="unique")
    op.drop_constraint(op.f("subscriptions_user_id_key"), "subscriptions", type_="unique")
    op.create_unique_constraint(
        "subscriptions_user_id_key",
        "subscriptions",
        ["user_id", "sign", "source"],
    )
    # ### end Alembic commands ###
